package tuloskortti.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.29 16:18:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa51 */
  @Test
  public void testLisaa51() {    // Kayttajat: 51
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja henkilo1 = new Kayttaja(); 
    Kayttaja henkilo2 = new Kayttaja(); 
    assertEquals("From: Kayttajat line: 55", 0, kayttajat.getLkm()); 
    try {
    kayttajat.lisaa(henkilo1); 
    } catch (SailoException e) {
    e.printStackTrace(); 
    }
    assertEquals("From: Kayttajat line: 63", 1, kayttajat.getLkm()); 
    try {
    kayttajat.lisaa(henkilo2); 
    } catch (SailoException e) {
    e.printStackTrace(); 
    }
    assertEquals("From: Kayttajat line: 71", 2, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 72", henkilo1, kayttajat.annaKayttaja(0)); 
    assertEquals("From: Kayttajat line: 73", henkilo2, kayttajat.annaKayttaja(1)); 
    assertEquals("From: Kayttajat line: 74", false, kayttajat.annaKayttaja(0) == henkilo2); 
    assertEquals("From: Kayttajat line: 75", true, kayttajat.annaKayttaja(0) == henkilo1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaTaiMuutaKayttaja90 */
  @Test
  public void testLisaaTaiMuutaKayttaja90() {    // Kayttajat: 90
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja kayttaja = new Kayttaja("Aku", "Ankka Gol", 2.1, 2001); 
    try {
    kayttajat.lisaaTaiMuutaKayttaja(kayttaja); 
    } catch (SailoException e) {
    e.printStackTrace(); 
    }
    Kayttaja kayttajaTesti = kayttajat.annaKayttaja(0); 
    assertEquals("From: Kayttajat line: 100", kayttaja.toString(), kayttajaTesti.toString()); 
    Kayttaja muokattuKayttaja = new Kayttaja("Aku", "Ankka Gol", 1.9, 2001); 
    try {
    kayttajat.lisaaTaiMuutaKayttaja(muokattuKayttaja); 
    } catch (SailoException e) {
    e.printStackTrace(); 
    }
    Kayttaja kayttajaTestiMuokattu = kayttajat.annaKayttaja(0); 
    assertEquals("From: Kayttajat line: 111", kayttaja.toString(), kayttajaTestiMuokattu.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta180 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta180() throws SailoException {    // Kayttajat: 180
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja aku = new Kayttaja(); 
    aku.taytaTestiTiedoilla(); 
    aku.rekisteroi(); 
    Kayttaja iines = new Kayttaja(); 
    iines.taytaTestiTiedoilla(); 
    iines.rekisteroi(); 
    String hakemisto = "testiGolfRekisteri"; 
    String tiedostonNimi = hakemisto + "/kayttaja"; 
    File fTiedosto = new File(tiedostonNimi + ".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    fTiedosto.delete(); 
    try {
    kayttajat.lueTiedostosta(tiedostonNimi); 
    fail("Kayttajat: 196 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kayttajat.lisaa(aku); 
    kayttajat.lisaa(iines); 
    kayttajat.tallenna(hakemisto); 
    assertEquals("From: Kayttajat line: 200", 2, kayttajat.getLkm()); 
    kayttajat = new Kayttajat();  // Tyhjennetään käyttäjät
    try {
    kayttajat.lueTiedostosta(tiedostonNimi); 
    fail("Kayttajat: 202 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kayttajat.lisaa(aku); 
    kayttajat.tallenna(hakemisto); 
    assertEquals("From: Kayttajat line: 205", true, fTiedosto.delete()); 
    assertEquals("From: Kayttajat line: 206", true, dir.delete()); 
  } // Generated by ComTest END
}