package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.29 16:18:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajaTest {



  // Generated by ComTest BEGIN
  /** testSetTunnusNro98 */
  @Test
  public void testSetTunnusNro98() {    // Kayttaja: 98
    Kayttaja kayttaja = new Kayttaja("Aku", "Ankka Gol", 2.1, 2001); 
    kayttaja.setTunnusNro(5); 
    assertEquals("From: Kayttaja line: 101", 5, kayttaja.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi179 */
  @Test
  public void testRekisteroi179() {    // Kayttaja: 179
    Kayttaja testi = new Kayttaja(); 
    assertEquals("From: Kayttaja line: 181", 0, testi.getTunnusNro()); 
    testi.rekisteroi(); 
    Kayttaja testi2 = new Kayttaja(); 
    testi2.rekisteroi(); 
    int n1 = testi.getTunnusNro(); 
    int n2 = testi2.getTunnusNro(); 
    assertEquals("From: Kayttaja line: 187", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString200 */
  @Test
  public void testToString200() {    // Kayttaja: 200
    Kayttaja kayttaja = new Kayttaja(); 
    kayttaja.parse("       3         |       Iines Ankka     |   Ankkalinna Golf"); 
    assertEquals("From: Kayttaja line: 203", true, kayttaja.toString().startsWith("3|Iines Ankka|Ankkalinna Golf")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse216 */
  @Test
  public void testParse216() {    // Kayttaja: 216
    Kayttaja kayttaja = new Kayttaja(); 
    kayttaja.parse("       3         |       Iines Ankka     |   Ankkalinna Golf"); 
    assertEquals("From: Kayttaja line: 219", 3, kayttaja.getTunnusNro()); 
    assertEquals("From: Kayttaja line: 220", true, kayttaja.toString().startsWith("3|Iines Ankka|Ankkalinna Golf")); 
    kayttaja.rekisteroi(); 
    int n = kayttaja.getTunnusNro(); 
    kayttaja.parse("" + (n + 20));  // Otetaan merkkijonon alusta vain id numero ja lisätään siihen 20
    kayttaja.rekisteroi();  // Tarkistetaan tämän jälkeen, että tulee isompi numero
    assertEquals("From: Kayttaja line: 225", n + 20 + 1, kayttaja.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone241 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone241() throws CloneNotSupportedException {    // Kayttaja: 241
    Kayttaja k1 = new Kayttaja(); 
    k1.parse("       4         |       Tupu Ankka     |   Ankkalinna Golf"); 
    Kayttaja kopio = k1.clone(); 
    assertEquals("From: Kayttaja line: 246", k1.toString(), kopio.toString()); 
    k1.parse("    1    | Iines Ankka    | Roope Golf"); 
    assertEquals("From: Kayttaja line: 248", false, kopio.toString().equals(k1.toString())); 
  } // Generated by ComTest END
}