package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.27 20:53:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa53 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa53() throws SailoException {    // Kayttajat: 53
    Kayttajat kayttajat = new Kayttajat(); 
    Kayttaja henkilo1 = new Kayttaja(); 
    Kayttaja henkilo2 = new Kayttaja(); 
    Kayttaja henkilo3 = new Kayttaja(); 
    assertEquals("From: Kayttajat line: 59", 0, kayttajat.getLkm()); 
    kayttajat.lisaa(henkilo1); assertEquals("From: Kayttajat line: 60", 1, kayttajat.getLkm()); 
    kayttajat.lisaa(henkilo2); assertEquals("From: Kayttajat line: 61", 2, kayttajat.getLkm()); 
    assertEquals("From: Kayttajat line: 62", henkilo1, kayttajat.annaKayttaja(0)); 
    assertEquals("From: Kayttajat line: 63", henkilo2, kayttajat.annaKayttaja(1)); 
    assertEquals("From: Kayttajat line: 64", false, kayttajat.annaKayttaja(0) == henkilo2); 
    assertEquals("From: Kayttajat line: 65", true, kayttajat.annaKayttaja(0) == henkilo1); 
    try {
    assertEquals("From: Kayttajat line: 66", henkilo1, kayttajat.annaKayttaja(5)); 
    fail("Kayttajat: 66 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    kayttajat.lisaa(henkilo3); 
    fail("Kayttajat: 67 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}