package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.22 21:52:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KayttajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi174 */
  @Test
  public void testRekisteroi174() {    // Kayttaja: 174
    Kayttaja testi = new Kayttaja(); 
    assertEquals("From: Kayttaja line: 176", 0, testi.getTunnusNro()); 
    testi.rekisteroi(); 
    Kayttaja testi2 = new Kayttaja(); 
    testi2.rekisteroi(); 
    int n1 = testi.getTunnusNro(); 
    int n2 = testi2.getTunnusNro(); 
    assertEquals("From: Kayttaja line: 182", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString195 */
  @Test
  public void testToString195() {    // Kayttaja: 195
    Kayttaja kayttaja = new Kayttaja(); 
    kayttaja.parse("       3         |       Iines Ankka     |   Ankkalinna Golf"); 
    assertEquals("From: Kayttaja line: 198", true, kayttaja.toString().startsWith("3|Iines Ankka|Ankkalinna Golf")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse211 */
  @Test
  public void testParse211() {    // Kayttaja: 211
    Kayttaja kayttaja = new Kayttaja(); 
    kayttaja.parse("       3         |       Iines Ankka     |   Ankkalinna Golf"); 
    assertEquals("From: Kayttaja line: 214", 3, kayttaja.getTunnusNro()); 
    assertEquals("From: Kayttaja line: 215", true, kayttaja.toString().startsWith("3|Iines Ankka|Ankkalinna Golf")); 
    kayttaja.rekisteroi(); 
    int n = kayttaja.getTunnusNro(); 
    kayttaja.parse("" + (n + 20));  // Otetaan merkkijonon alusta vain id numero ja lisätään siihen 20
    kayttaja.rekisteroi();  // Tarkistetaan tämän jälkeen, että tulee isompi numero
    assertEquals("From: Kayttaja line: 220", n + 20 + 1, kayttaja.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone236 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone236() throws CloneNotSupportedException {    // Kayttaja: 236
    Kayttaja k1 = new Kayttaja(); 
    k1.parse("       4         |       Tupu Ankka     |   Ankkalinna Golf"); 
    Kayttaja kopio = k1.clone(); 
    assertEquals("From: Kayttaja line: 241", k1.toString(), kopio.toString()); 
    k1.parse("    1    | Iines Ankka    | Roope Golf"); 
    assertEquals("From: Kayttaja line: 243", false, kopio.toString().equals(k1.toString())); 
  } // Generated by ComTest END
}