package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.21 15:28:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosTest {



  // Generated by ComTest BEGIN
  /** testToString93 */
  @Test
  public void testToString93() {    // Kierros: 93
    Kierros k = new Kierros(); 
    k.parse("       3         |       4    |   1"); 
    assertEquals("From: Kierros line: 96", true, k.toString().startsWith("3|4|1")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi204 */
  @Test
  public void testRekisteroi204() {    // Kierros: 204
    Kierros kierros1 = new Kierros(); 
    assertEquals("From: Kierros line: 206", 0, kierros1.getTunnusNro()); 
    kierros1.rekisteroi(); 
    Kierros kierros2 = new Kierros(); 
    kierros2.rekisteroi(); 
    int n1 = kierros1.getTunnusNro(); 
    int n2 = kierros2.getTunnusNro(); 
    assertEquals("From: Kierros line: 212", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse226 */
  @Test
  public void testParse226() {    // Kierros: 226
    Kierros kierros = new Kierros(); 
    assertEquals("From: Kierros line: 229", 3, kierros.getTunnusNro()); 
    assertEquals("From: Kierros line: 230", true, kierros.toString().startsWith("3|1|1")); 
    kierros.rekisteroi(); 
    int n = kierros.getTunnusNro(); 
    kierros.parse("" + (n + 20));  // Otetaan merkkijonon alusta vain id numero ja lisätään siihen 20
    kierros.rekisteroi();  // Tarkistetaan tämän jälkeen, että tulee isompi numero
    assertEquals("From: Kierros line: 235", n + 20 + 1, kierros.getTunnusNro()); 
  } // Generated by ComTest END
}