package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.13 17:25:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi91 */
  @Test
  public void testRekisteroi91() {    // Kierros: 91
    Kierros kierros1 = new Kierros(); 
    assertEquals("From: Kierros line: 93", 0, kierros1.getTunnusNro()); 
    kierros1.rekisteroi(); 
    Kierros kierros2 = new Kierros(); 
    kierros2.rekisteroi(); 
    int n1 = kierros1.getTunnusNro(); 
    int n2 = kierros2.getTunnusNro(); 
    assertEquals("From: Kierros line: 99", n2-1, n1); 
  } // Generated by ComTest END
}