package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.14 20:36:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierroksetTest {



  // Generated by ComTest BEGIN
  /** testAnnaKierrokset71 */
  @Test
  public void testAnnaKierrokset71() {    // Kierrokset: 71
    Kierrokset kierrokset = new Kierrokset(); 
    Kierros kierros1 = new Kierros(); 
    kierros1.taytaTestiTiedoilla(1, 1, 2, 4, 55); 
    Kierros kierros2 = new Kierros(); 
    kierros2.taytaTestiTiedoilla(2, 1, 2, 4, 48); 
    kierrokset.lisaaKierros(kierros1); 
    kierrokset.lisaaKierros(kierros2); 
    List<Kierros> loytyneet; 
    loytyneet = kierrokset.annaKierrokset(1, 1); 
    loytyneet = kierrokset.annaKierrokset(2, 1); 
    assertEquals("From: Kierrokset line: 84", true, loytyneet.get(0) == kierros1); 
    assertEquals("From: Kierrokset line: 85", true, loytyneet.get(1) == kierros2); 
  } // Generated by ComTest END
}