package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.*;
import kanta.UusiKierros;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.27 20:53:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierroksetTest {



  // Generated by ComTest BEGIN
  /** testAnnaKierrokset89 */
  @Test
  public void testAnnaKierrokset89() {    // Kierrokset: 89
    Kierrokset kierrokset = new Kierrokset(); 
    kierrokset.lisaaKierros(UusiKierros.luoKierros(1, 55)); 
    List<Kierros> loytyneet; 
    loytyneet = kierrokset.annaKierrokset(1, 1); 
    assertEquals("From: Kierrokset line: 97", 18, loytyneet.size()); 
    kierrokset.lisaaKierros(UusiKierros.luoKierros(1, 55)); 
    loytyneet = kierrokset.annaKierrokset(1, 1); 
    assertEquals("From: Kierrokset line: 100", 36, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKaikkiKierrokset118 */
  @Test
  public void testAnnaKaikkiKierrokset118() {    // Kierrokset: 118
    Kierrokset kierrokset = new Kierrokset(); 
    kierrokset.lisaaKierros(UusiKierros.luoKierros(1, 55)); 
    Collection<Kierros> kierrosYksiRivi = kierrokset.annaKaikkiKierrokset(); 
    assertEquals("From: Kierrokset line: 125", 18, kierrosYksiRivi.size()); 
  } // Generated by ComTest END
}