package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.15 16:13:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SeuratTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa53 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa53() throws SailoException {    // Seurat: 53
    Seurat seurat = new Seurat(); 
    Seura seura1 = new Seura(); 
    Seura seura2 = new Seura(); 
    Seura seura3 = new Seura(); 
    Seura seura4 = new Seura(); 
    Seura seura5 = new Seura(); 
    Seura seura6 = new Seura(); 
    assertEquals("From: Seurat line: 62", 0, seurat.getLkm()); 
    seurat.lisaa(seura1); assertEquals("From: Seurat line: 63", 1, seurat.getLkm()); 
    seurat.lisaa(seura2); assertEquals("From: Seurat line: 64", 2, seurat.getLkm()); 
    assertEquals("From: Seurat line: 65", seura1, seurat.annaSeura(0)); 
    assertEquals("From: Seurat line: 66", seura2, seurat.annaSeura(1)); 
    assertEquals("From: Seurat line: 67", false, seurat.annaSeura(0) == seura2); 
    assertEquals("From: Seurat line: 68", true, seurat.annaSeura(0) == seura1); 
    seurat.lisaa(seura3); 
    seurat.lisaa(seura3); 
    seurat.lisaa(seura3); 
    seurat.lisaa(seura4); 
    seurat.lisaa(seura5); 
    seurat.lisaa(seura6); 
    assertEquals("From: Seurat line: 75", 8, seurat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaSeurat144 */
  @Test
  public void testAnnaSeurat144() {    // Seurat: 144
    Seurat seurat = new Seurat(); 
    List<Seura> loytyneet; 
    Seura seura1 = new Seura(); 
    seura1.rekisteroi(); 
    seura1.taytaTestiTiedoilla(); 
    loytyneet = seurat.annaSeurat(); 
    assertEquals("From: Seurat line: 155", 1, loytyneet.size()); 
    Seura seura2 = new Seura(); 
    seura2.rekisteroi(); 
    seura2.taytaTestiTiedoilla(); 
    loytyneet = seurat.annaSeurat(); 
    assertEquals("From: Seurat line: 161", 2, loytyneet.size()); 
  } // Generated by ComTest END
}