package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.12 18:43:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SeuraTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi86 */
  @Test
  public void testRekisteroi86() {    // Seura: 86
    Seura seura = new Seura(); 
    assertEquals("From: Seura line: 88", 0, seura.getTunnusNro()); 
    seura.rekisteroi(); 
    Seura seura2 = new Seura(); 
    seura2.rekisteroi(); 
    int n1 = seura.getTunnusNro(); 
    int n2 = seura2.getTunnusNro(); 
    assertEquals("From: Seura line: 94", n2-1, n1); 
  } // Generated by ComTest END
}