package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.29 16:26:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SeuratTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa55 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa55() throws SailoException {    // Seurat: 55
    Seurat seurat = new Seurat(); 
    Seura seura1 = new Seura(); 
    Seura seura2 = new Seura(); 
    Seura seura3 = new Seura(); 
    Seura seura4 = new Seura(); 
    Seura seura5 = new Seura(); 
    Seura seura6 = new Seura(); 
    assertEquals("From: Seurat line: 64", 0, seurat.getLkm()); 
    seurat.lisaa(seura1); assertEquals("From: Seurat line: 65", 1, seurat.getLkm()); 
    seurat.lisaa(seura2); assertEquals("From: Seurat line: 66", 2, seurat.getLkm()); 
    assertEquals("From: Seurat line: 67", seura1, seurat.annaSeura(0)); 
    assertEquals("From: Seurat line: 68", seura2, seurat.annaSeura(1)); 
    assertEquals("From: Seurat line: 69", false, seurat.annaSeura(0) == seura2); 
    assertEquals("From: Seurat line: 70", true, seurat.annaSeura(0) == seura1); 
    seurat.lisaa(seura3); 
    seurat.lisaa(seura3); 
    seurat.lisaa(seura3); 
    seurat.lisaa(seura4); 
    seurat.lisaa(seura5); 
    seurat.lisaa(seura6); 
    assertEquals("From: Seurat line: 77", 8, seurat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaSeurat131 */
  @Test
  public void testAnnaSeurat131() {    // Seurat: 131
    Seurat seurat = new Seurat(); 
    List<Seura> loytyneet; 
    Seura seura1 = new Seura(); 
    seura1.rekisteroi(); 
    seura1.taytaTestiTiedoilla(); 
    seurat.lisaa(seura1); 
    loytyneet = seurat.annaSeurat(); 
    assertEquals("From: Seurat line: 142", 1, loytyneet.size()); 
    Seura seura2 = new Seura(); 
    seura2.rekisteroi(); 
    seura2.taytaTestiTiedoilla(); 
    seurat.lisaa(seura2); 
    loytyneet = seurat.annaSeurat(); 
    assertEquals("From: Seurat line: 148", 2, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta192 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta192() throws SailoException {    // Seurat: 192
    Seurat seurat = new Seurat(); 
    Seura seura1 = new Seura(); 
    seura1.taytaTestiTiedoilla(); 
    seura1.rekisteroi(); 
    Seura seura2 = new Seura(); 
    seura2.taytaTestiTiedoilla(); 
    seura2.rekisteroi(); 
    String hakemisto = "testiGolfRekisteri"; 
    String tiedostonNimi = hakemisto + "/seura"; 
    File fTiedosto = new File(tiedostonNimi + ".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    fTiedosto.delete(); 
    try {
    seurat.lueTiedostosta(tiedostonNimi); 
    fail("Seurat: 208 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    seurat.lisaa(seura1); 
    seurat.lisaa(seura2); 
    seurat.tallenna(hakemisto); 
    assertEquals("From: Seurat line: 212", 2, seurat.getLkm()); 
    seurat = new Seurat();  // Tyhjennetään seurat
    try {
    seurat.lueTiedostosta(tiedostonNimi); 
    fail("Seurat: 214 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    seurat.lisaa(seura1); 
    seurat.tallenna(hakemisto); 
    assertEquals("From: Seurat line: 217", true, fTiedosto.delete()); 
    assertEquals("From: Seurat line: 218", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaTaiMuutaSeura247 */
  @Test
  public void testLisaaTaiMuutaSeura247() {    // Seurat: 247
    Seurat seurat = new Seurat(); 
    Seura seura1 = new Seura(); 
    Seura seura2 = new Seura(); 
    try {
    seurat.lisaaTaiMuutaSeura(seura1); 
    } catch (SailoException e) {
    e.printStackTrace(); 
    }
    assertEquals("From: Seurat line: 257", 1, seurat.getLkm()); 
    try {
    seurat.lisaaTaiMuutaSeura(seura2); 
    } catch (SailoException e) {
    e.printStackTrace(); 
    }
    assertEquals("From: Seurat line: 264", 1, seurat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaSeura319 */
  @Test
  public void testPoistaSeura319() {    // Seurat: 319
    Seurat seurat = new Seurat(); 
    Seura seura1 = new Seura(); 
    seura1.rekisteroi(); 
    Seura seura2 = new Seura(); 
    seura2.rekisteroi(); 
    seurat.lisaa(seura1); 
    seurat.lisaa(seura2); 
    assertEquals("From: Seurat line: 328", 2, seurat.getLkm()); 
    int tulos1 = seurat.poistaSeura(1); 
    assertEquals("From: Seurat line: 331", 0, tulos1); 
    int tulos2 = seurat.poistaSeura(2); 
    assertEquals("From: Seurat line: 334", 0, tulos2); 
  } // Generated by ComTest END
}