package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.13 16:59:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuloskorttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi96 */
  @Test
  public void testRekisteroi96() {    // Tuloskortti: 96
    Tuloskortti tuloskortti1 = new Tuloskortti(); 
    assertEquals("From: Tuloskortti line: 98", 0, tuloskortti1.getTunnusNro()); 
    tuloskortti1.rekisteroi(); 
    Tuloskortti tuloskortti2 = new Tuloskortti(); 
    tuloskortti2.rekisteroi(); 
    int n1 = tuloskortti1.getTunnusNro(); 
    int n2 = tuloskortti2.getTunnusNro(); 
    assertEquals("From: Tuloskortti line: 104", n2-1, n1); 
  } // Generated by ComTest END
}