package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.27 20:55:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuloskortitTest {



  // Generated by ComTest BEGIN
  /** testAnnaTuloskortit86 */
  @Test
  public void testAnnaTuloskortit86() {    // Tuloskortit: 86
    Tuloskortit tuloskortit = new Tuloskortit(); 
    Tuloskortti vayla1 = new Tuloskortti(2,1,433,407,387,387,5,1); 
    tuloskortit.lisaaTuloskortti(vayla1); 
    Tuloskortti vayla2 = new Tuloskortti(2,2,119,117,115,115,3,4); 
    tuloskortit.lisaaTuloskortti(vayla2); 
    Tuloskortti vayla3 = new Tuloskortti(2,3,320,308,308,284,4,9); 
    tuloskortit.lisaaTuloskortti(vayla3); 
    List<Tuloskortti> loytyneet; 
    loytyneet = tuloskortit.annaTuloskortit(3); 
    assertEquals("From: Tuloskortit line: 99", 0, loytyneet.size()); 
    loytyneet = tuloskortit.annaTuloskortit(2); 
    assertEquals("From: Tuloskortit line: 101", 3, loytyneet.size()); 
    assertEquals("From: Tuloskortit line: 102", true, loytyneet.get(0) == vayla1); 
    assertEquals("From: Tuloskortit line: 103", true, loytyneet.get(1) == vayla2); 
  } // Generated by ComTest END
}