package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.27 20:56:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuloskorttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi157 */
  @Test
  public void testRekisteroi157() {    // Tuloskortti: 157
    Tuloskortti tuloskortti1 = new Tuloskortti(); 
    assertEquals("From: Tuloskortti line: 159", 0, tuloskortti1.getTunnusNro()); 
    tuloskortti1.rekisteroi(); 
    Tuloskortti tuloskortti2 = new Tuloskortti(); 
    tuloskortti2.rekisteroi(); 
    int n1 = tuloskortti1.getTunnusNro(); 
    int n2 = tuloskortti2.getTunnusNro(); 
    assertEquals("From: Tuloskortti line: 165", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse179 */
  @Test
  public void testParse179() {    // Tuloskortti: 179
    Tuloskortti tuloskortti = new Tuloskortti(); 
    assertEquals("From: Tuloskortti line: 182", 3, tuloskortti.getTunnusNro()); 
    assertEquals("From: Tuloskortti line: 183", true, tuloskortti.toString().startsWith("3|1|1")); 
    tuloskortti.rekisteroi(); 
    int n = tuloskortti.getTunnusNro(); 
    tuloskortti.parse("" + (n + 20));  // Otetaan merkkijonon alusta vain id numero ja lisätään siihen 20
    tuloskortti.rekisteroi();  // Tarkistetaan tämän jälkeen, että tulee isompi numero
    assertEquals("From: Tuloskortti line: 188", n + 20 + 1, tuloskortti.getTunnusNro()); 
  } // Generated by ComTest END
}