package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.29 16:22:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuloskorttiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi252 */
  @Test
  public void testRekisteroi252() {    // Tuloskortti: 252
    Tuloskortti tuloskortti1 = new Tuloskortti(); 
    assertEquals("From: Tuloskortti line: 254", 0, tuloskortti1.getTunnusNro()); 
    tuloskortti1.rekisteroi(); 
    Tuloskortti tuloskortti2 = new Tuloskortti(); 
    tuloskortti2.rekisteroi(); 
    int n1 = tuloskortti1.getTunnusNro(); 
    int n2 = tuloskortti2.getTunnusNro(); 
    assertEquals("From: Tuloskortti line: 260", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse274 */
  @Test
  public void testParse274() {    // Tuloskortti: 274
    Tuloskortti tuloskortti = new Tuloskortti(); 
    assertEquals("From: Tuloskortti line: 277", 0, tuloskortti.getTunnusNro()); 
    assertEquals("From: Tuloskortti line: 278", false, tuloskortti.toString().startsWith("3|1|1")); 
    tuloskortti.rekisteroi(); 
    int n = tuloskortti.getTunnusNro(); 
    tuloskortti.parse("" + (n + 20));  // Otetaan merkkijonon alusta vain id numero ja lisätään siihen 20
    tuloskortti.rekisteroi();  // Tarkistetaan tämän jälkeen, että tulee isompi numero
    assertEquals("From: Tuloskortti line: 283", n + 20 + 1, tuloskortti.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone303 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone303() throws CloneNotSupportedException {    // Tuloskortti: 303
    Tuloskortti tuloskortti = new Tuloskortti(1, 1, 190, 140, 120, 120, 3, 5); 
    Tuloskortti kopio = tuloskortti.clone(); 
    assertEquals("From: Tuloskortti line: 307", tuloskortti.toString(), kopio.toString()); 
    assertEquals("From: Tuloskortti line: 308", true, kopio.toString().equals(tuloskortti.toString())); 
  } // Generated by ComTest END
}